{{- if .Values.mcp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmemory.fullname" . }}-mcp
  labels:
    {{- include "openmemory.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
spec:
  {{- if not .Values.mcp.autoscaling.enabled }}
  replicas: {{ .Values.mcp.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if eq .Values.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "openmemory.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp
  template:
    metadata:
      labels:
        {{- include "openmemory.labels" . | nindent 8 }}
        app.kubernetes.io/component: mcp
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openmemory.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mcp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.mcp.image.repository }}:{{ .Values.mcp.image.tag }}"
          imagePullPolicy: {{ .Values.mcp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mcp.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.mcp.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.mcp.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /app/cache
          resources:
            {{- toYaml .Values.mcp.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
      {{- with .Values.mcp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
