{{- if and .Values.mcp.enabled .Values.mcp.ingress.enabled -}}
{{- $fullName := include "openmemory.fullname" . -}}
{{- $svcPort := .Values.mcp.service.port -}}
{{- if and .Values.mcp.ingress.className (not (hasKey .Values.mcp.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.mcp.ingress.annotations "kubernetes.io/ingress.class" .Values.mcp.ingress.className}}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-mcp
  labels:
    {{- include "openmemory.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
  {{- with .Values.mcp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.mcp.ingress.className }}
  ingressClassName: {{ .Values.mcp.ingress.className }}
  {{- end }}
  {{- if .Values.mcp.ingress.tls }}
  tls:
    {{- range .Values.mcp.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.mcp.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}-mcp
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
