{{- if and .Values.mcp.enabled .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openmemory.fullname" . }}-mcp
  labels:
    {{- include "openmemory.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
spec:
  podSelector:
    matchLabels:
      {{- include "openmemory.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.mcp.service.targetPort }}
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: qdrant
      ports:
        - protocol: TCP
          port: 6333
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
