# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "quickpizza.fullname" . }}-env
  namespace: {{ template "quickpizza.namespace" . }}
  labels:
    {{- include "quickpizza.labels" . | indent 4 }}
    app.kubernetes.io/component: commons
data:
  QUICKPIZZA_TRUST_CLIENT_TRACEID: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "quickpizza.fullname" . }}-telemetry
  namespace: {{ template "quickpizza.namespace" . }}
  labels:
    {{- include "quickpizza.labels" . | indent 4 }}
    app.kubernetes.io/component: commons
data:
  QUICKPIZZA_LOG_LEVEL: {{ .Values.config.logLevel }}
  QUICKPIZZA_OTLP_ENDPOINT: {{ .Values.config.otlp }}
  QUICKPIZZA_CONF_FARO_URL: {{ .Values.config.faro }}
