# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "quickpizza.labels" . | indent 4 }}
    {{- include "quickpizza.frontend.labels" . | nindent 4 }}
  name: {{ template "quickpizza.fullname" . }}-frontend
  namespace: {{ template "quickpizza.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quickpizza.selectorLabels" . | indent 4 }}
    {{- include "quickpizza.frontend.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "quickpizza.labels" . | indent 4 }}
    {{- include "quickpizza.config.labels" . | nindent 4 }}
  name: {{ template "quickpizza.fullname" . }}-config
  namespace: {{ template "quickpizza.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quickpizza.selectorLabels" . | indent 4 }}
    {{- include "quickpizza.config.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "quickpizza.labels" . | indent 4 }}
    {{- include "quickpizza.ws.labels" . | nindent 4 }}
  name: {{ template "quickpizza.fullname" . }}-ws
  namespace: {{ template "quickpizza.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quickpizza.selectorLabels" . | indent 4 }}
    {{- include "quickpizza.ws.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "quickpizza.labels" . | indent 4 }}
    {{- include "quickpizza.catalog.labels" . | nindent 4 }}
  name: {{ template "quickpizza.fullname" . }}-catalog
  namespace: {{ template "quickpizza.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quickpizza.selectorLabels" . | indent 4 }}
    {{- include "quickpizza.catalog.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "quickpizza.labels" . | indent 4 }}
    {{- include "quickpizza.copy.labels" . | nindent 4 }}
  name: {{ template "quickpizza.fullname" . }}-copy
  namespace: {{ template "quickpizza.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quickpizza.selectorLabels" . | indent 4 }}
    {{- include "quickpizza.copy.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "quickpizza.labels" . | indent 4 }}
    {{- include "quickpizza.recs.labels" . | nindent 4 }}
  name: {{ template "quickpizza.fullname" . }}-recs
  namespace: {{ template "quickpizza.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quickpizza.selectorLabels" . | indent 4 }}
    {{- include "quickpizza.recs.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
