---
apiVersion: v2
description: Traefik CRDs
name: traefik-crds
version: 1.0.0
# renovate: datasource=github-tags depName=traefik/traefik
appVersion: v30.0.2
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
sources:
- https://github.com/portefaix/portefaix-hub
- https://github.com/traefik/traefik
keywords:
- traefik
- crds

dependencies:
- name: crds
  version: "0.0.0"

maintainers:
- name: nlamirault
  email: nicolas.lamirault@gmail.com
  url: https://github.com/nlamirault

# https://artifacthub.io/docs/topics/repositories/
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Traefik
      url: https://traefik.io/
    - name: Portefaix Hub
      url: https://github.com/portefaix/portefaix-hub
  artifacthub.io/maintainers: |
    - name: nlamirault
      email: nicolas.lamirault@gmail.com
  artifacthub.io/signKey: |
    fingerprint: C39918B3EBDE35C23B8D0B8E5F99269A6FCA437C
    url: https://keybase.io/nlamirault/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: added
      description: Init chart
