---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "linkerd-stable-mixin.fullname" .) "alerts" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "linkerd-stable-mixin.namespace" . }}
  annotations:
    {{- include "linkerd-stable-mixin.annotations" . | indent 4 }}
  labels:
    {{- include "linkerd-stable-mixin.labels" . | indent 4 }}
    {{- if .Values.monitor.additionalLabels }}
    {{- toYaml .Values.monitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
      - name: linkerd
        rules:
          - alert: LinkerdRequestsHighErrorRate
            annotations:
              message: Linkerd error rate for {{`{{`}} $labels.deployment | $labels.statefulset | $labels.daemonset {{`}}`}}.
              runbook_url: https://github.com/nlamiraut/monitoring-mixins/tree/master/mixins/linkerd-stable-mixin/runbook.md#alert-name-linkerdrequestshigherrorrate
              summary: Linkerd have high error rate for more than 10 minutes.
            expr: sum(rate(request_errors_total[1m])) by (deployment, statefulset, daemonset) / sum(rate(request_total[1m])) by (deployment, statefulset, daemonset) * 100 > 10
            for: 10m
            labels:
              severity: warning
