---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "loki-mixin.labels" . | indent 4 }}
    {{- if .Values.monitor.additionalLabels }}
    {{- toYaml .Values.monitor.additionalLabels | nindent 4 }}
    {{- end }}
  name: {{ printf "%s-%s" (include "loki-mixin.fullname" .) "rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "loki-mixin.namespace" . }}
spec:
  groups:
      - name: loki_rules
        rules:
          - expr: histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, cluster, job))
            record: cluster_job:loki_request_duration_seconds:99quantile
          - expr: histogram_quantile(0.50, sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, cluster, job))
            record: cluster_job:loki_request_duration_seconds:50quantile
          - expr: sum(rate(loki_request_duration_seconds_sum[1m])) by (cluster, job) / sum(rate(loki_request_duration_seconds_count[1m])) by (cluster, job)
            record: cluster_job:loki_request_duration_seconds:avg
          - expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, cluster, job)
            record: cluster_job:loki_request_duration_seconds_bucket:sum_rate
          - expr: sum(rate(loki_request_duration_seconds_sum[1m])) by (cluster, job)
            record: cluster_job:loki_request_duration_seconds_sum:sum_rate
          - expr: sum(rate(loki_request_duration_seconds_count[1m])) by (cluster, job)
            record: cluster_job:loki_request_duration_seconds_count:sum_rate
          - expr: histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, cluster, job, route))
            record: cluster_job_route:loki_request_duration_seconds:99quantile
          - expr: histogram_quantile(0.50, sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, cluster, job, route))
            record: cluster_job_route:loki_request_duration_seconds:50quantile
          - expr: sum(rate(loki_request_duration_seconds_sum[1m])) by (cluster, job, route) / sum(rate(loki_request_duration_seconds_count[1m])) by (cluster, job, route)
            record: cluster_job_route:loki_request_duration_seconds:avg
          - expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, cluster, job, route)
            record: cluster_job_route:loki_request_duration_seconds_bucket:sum_rate
          - expr: sum(rate(loki_request_duration_seconds_sum[1m])) by (cluster, job, route)
            record: cluster_job_route:loki_request_duration_seconds_sum:sum_rate
          - expr: sum(rate(loki_request_duration_seconds_count[1m])) by (cluster, job, route)
            record: cluster_job_route:loki_request_duration_seconds_count:sum_rate
          - expr: histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, cluster, namespace, job, route))
            record: cluster_namespace_job_route:loki_request_duration_seconds:99quantile
          - expr: histogram_quantile(0.50, sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, cluster, namespace, job, route))
            record: cluster_namespace_job_route:loki_request_duration_seconds:50quantile
          - expr: sum(rate(loki_request_duration_seconds_sum[1m])) by (cluster, namespace, job, route) / sum(rate(loki_request_duration_seconds_count[1m])) by (cluster, namespace, job, route)
            record: cluster_namespace_job_route:loki_request_duration_seconds:avg
          - expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, cluster, namespace, job, route)
            record: cluster_namespace_job_route:loki_request_duration_seconds_bucket:sum_rate
          - expr: sum(rate(loki_request_duration_seconds_sum[1m])) by (cluster, namespace, job, route)
            record: cluster_namespace_job_route:loki_request_duration_seconds_sum:sum_rate
          - expr: sum(rate(loki_request_duration_seconds_count[1m])) by (cluster, namespace, job, route)
            record: cluster_namespace_job_route:loki_request_duration_seconds_count:sum_rate
