---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "grafana-mixin.fullname" .) "alerts" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "grafana-mixin.namespace" . }}
  annotations:
    {{- include "grafana-mixin.annotations" . | indent 4 }}
  labels:
    {{- include "grafana-mixin.labels" . | indent 4 }}
    {{- if .Values.monitor.additionalLabels }}
    {{- toYaml .Values.monitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
      - name: GrafanaAlerts
        rules:
          - alert: GrafanaRequestsFailing
            annotations:
              message: '{{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.job {{`}}`}}/{{`{{`}} $labels.handler {{`}}`}} is experiencing {{`{{`}} $value | humanize {{`}}`}}% errors'
            expr: |
              100 * sum without (status_code) (namespace_job_handler_statuscode:grafana_http_request_duration_seconds_count:rate5m{handler!~"/api/datasources/proxy/:id.*|/api/ds/query|/api/tsdb/query", status_code=~"5.."})
              /
              sum without (status_code) (namespace_job_handler_statuscode:grafana_http_request_duration_seconds_count:rate5m{handler!~"/api/datasources/proxy/:id.*|/api/ds/query|/api/tsdb/query"})
              > 50
            for: 5m
            labels:
              severity: warning
