---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "grafana-mixin.fullname" .) "rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "grafana-mixin.namespace" . }}
  annotations:
    {{- include "grafana-mixin.annotations" . | indent 4 }}
  labels:
    {{- include "grafana-mixin.labels" . | indent 4 }}
    {{- if .Values.monitor.additionalLabels }}
    {{- toYaml .Values.monitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
      - name: grafana_rules
        rules:
          - expr: |
              sum by (namespace, job, handler, status_code) (rate(grafana_http_request_duration_seconds_count[5m]))
            record: namespace_job_handler_statuscode:grafana_http_request_duration_seconds_count:rate5m
