- action: Terminate Pod
  actionner: kubernetes:terminate

- action: Label Pod as Suspicious
  actionner: kubernetes:label
  parameters:
    labels:
      falco-talon.org/suspicious: "true"

- rule: Terminal shell in container 
  match:
    rules:
      - Terminal shell in container
    output_fields:
      - k8s.ns.name!=kube-system, k8s.ns.name!=falco
  actions:
    - action: Label Pod as Suspicious
