# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
# Default values for kcc-factory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Additional labels to add to all resources
additionalLabels: {}
  # app: kcc

# -- Additional annotations to add to all resources
additionalAnnotations: {}

kcc:
  network:
    routingMode: REGIONAL
    region: eu-west1
    ipCidrRange: 10.2.0.0/16
    secondaryIpRange:
    - ipCidrRange: 10.3.0.0/16
      rangeName: services
    - ipCidrRange: 10.4.0.0/16
      rangeName: pods

  artifactregistry:
  - name: charts
    format: DOCKER
    location: eu-west1
  - name: containers
    format: DOCKER
    location: eu-west1

  pubsub:
    topics:
    - name: gke-update

  buckets:
  - name: logs
    location: eu-west1
    storageClass: standard
    versioning: true
    lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 10

  gke:
    location: eu-west1
    releaseChannel: REGULAR

    # Automation

    clusterAutoscaling:
      enabled: true
      autoscalingProfile: BALANCED
      resourceLimits:
      - resourceType: cpu
        maximum: 100
        minimum: 10
      - resourceType: memory
        maximum: 1000
        minimum: 100
    verticalPodAutoscaling:
      enabled: false
    maintenancePolicy:
      dailyMaintenanceWindow:
        startTime: 03:00
    notificationConfig:
      pubsub:
        enabled: true
        topicRef:
          name: kcc-factory-gke-update

    # Node Pools

    defaultNodepools:
      initialNodeCount: 0
      defaultMaxPodsPerNode: 16
      nodeLocations:
        - eu-west1-a
        - eu-west1-b
        - eu-west1-c

    # Networking

    networkingMode: VPC_NATIVE
    datapathProvider: ADVANCED_DATAPATH
    masterAuthorizedNetworksConfig:
      cidrBlocks:
        - cidrBlock: 0.0.0.0/0
          displayName: The Internet
    ipAllocationPolicy:
      servicesSecondaryRangeName: services
      clusterSecondaryRangeName: pods
    networkPolicy:
      enabled: true

    # NodePool

    nodepools:
    - name: core
      autoscaling:
        minNodeCount: 1
        maxNodeCount: 3
      machineType: e2-standard-16
      diskSizeGb: 100
      diskType: pd-ssd
      preemptible: false
    - name: ops
      autoscaling:
        minNodeCount: 1
        maxNodeCount: 3
      machineType: e2-standard-16
      diskSizeGb: 100
      diskType: pd-ssd
      preemptible: true
