{{- if .Values.aws.enabled }}
---
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: s3bucket.aws.kro.run
  namespace: {{ template "kro-factory.namespace" . }}
  labels:
    {{- include "kro-factory.labels" . | nindent 4 }}
    {{- include "kro.aws.labels" . | nindent 4 }}
    {{- with .Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  schema:
    apiVersion: v1alpha1
    kind: S3Bucket
    spec:
      name: string
      namespace: string
      metadata:
        labels: 'map[string]string'
        annotations: 'map[string]string'
      access: string | default="write"
    status:
      s3ARN: ${s3bucket.status.ackResourceMetadata.arn}
      s3PolicyARN: ${s3PolicyWrite.status.ackResourceMetadata.arn}

  resources:

  - id: s3bucket
    template:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        annotations: ${schema.spec.metadata.annotations}
        labels: ${schema.spec.metadata.labels}
      spec:
        name: ${schema.spec.access}

  - id: s3PolicyWrite
    includeWhen:
    - ${schema.spec.access == "write"}
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Policy
      metadata:
        name: ${schema.spec.name}-s3-write-policy
        namespace: ${schema.spec.namespace}
        annotations: ${schema.spec.metadata.annotations}
        labels: ${schema.spec.metadata.labels}
      spec:
        name: ${schema.spec.name}-s3-write-policy
        policyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:GetObject",
                  "s3:PutObject",
                  "s3:PutObjectAcl",
                  "s3:DeleteObject"
                ],
                "Resource": [
                  "${s3bucket.status.ackResourceMetadata.arn}/*"
                ]
              },
              {
                "Effect": "Allow",
                "Action": [
                  "s3:ListBucket",
                  "s3:GetBucketLocation"
                ],
                "Resource": [
                  "${s3bucket.status.ackResourceMetadata.arn}"
                ]
              }
            ]
          }
{{- end }}
