---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencost.fullname" . }}
  namespace: {{ template "opencost.namespace" . }}
  {{- if or .Values.service.annotations .Values.additionalAnnotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 4 }}
  {{- with .Values.additionalAnnotations }}
  {{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "opencost.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opencost.selectorLabels" . | indent 4 }}
