{{- if .Values.rbac.create }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8sgpt.fullname" . }}
  namespace: {{ template "k8sgpt.namespace" . }}
  {{- if .Values.additionalAnnotations }}
  annotations:
  {{ toYaml .Values.additionalAnnotations | indent 4 }}
  {{- end }}
  labels:
    app: k8sgpt
    {{- include "k8sgpt.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "k8sgpt.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "k8sgpt.fullname" . }}
{{- end }}
