{{- if .Values.chatgpt.secret.created }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chatgpt.secret.name }}
  namespace: {{ template "k8sgpt.namespace" . }}
  {{- if .Values.additionalAnnotations }}
  annotations:
  {{ toYaml .Values.additionalAnnotations | indent 4 }}
  {{- end }}
  labels:
    app: k8sgpt
    {{- include "k8sgpt.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.chatgpt.secret.key }}: "{{ .Values.chatgpt.secret.value | b64enc }}"
{{- end }}
