{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: k8sgpt
    {{- include "k8sgpt.labels" . | indent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{ toYaml .Values.serviceMonitor.additionalLabels }}
    {{- end }}
  name: {{ template "k8sgpt.fullname" .  }}
  namespace: {{ template "k8sgpt.namespace" . }}
spec:
  jobLabel: {{ template "k8sgpt.fullname" . }}
  endpoints:
  - port: http
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- if .Values.serviceMonitor.honorLabels }}
    honorLabels: true
    {{- end }}
  selector:
    matchLabels:
      {{- include "k8sgpt.selectorLabels" . | indent 6 }}
{{- end }}
