{
 "title": "Cilium / Components / L3 Policy",
 "description": "Dashboard for Cilium v1.12 (https://cilium.io/) Agent metrics",
 "tags": [
  "cilium-agent",
  "portefaix",
  "cilium",
  "cilium-mixin",
  "cni",
  "ebpf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cilium_version, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "label": "top k", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Top Pod Ingress Packet Forward Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_forward_count_total{k8s_app=\"cilium\", direction=\"INGRESS\", pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Drop Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, avg(rate(cilium_drop_count_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, direction))",
     "legendFormat": "{{pod}}:{{direction}}"
    }
   ]
  },
  {
   "title": "Egress Packet Drop Reasons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{k8s_app=\"cilium\", direction=\"EGRESS\", pod=~\"$pod\"}[$__rate_interval])) by (reason)",
     "legendFormat": "Reason: {{reason}}"
    },
    {
     "expr": "sum(rate(cilium_forward_count_total{k8s_app=\"cilium\", direction=\"EGRESS\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Forwarded"
    }
   ]
  },
  {
   "title": "Ingress Packets by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{k8s_app=\"cilium\", direction=\"INGRESS\"}[$__rate_interval])) by (reason)",
     "legendFormat": "Reason: {{reason}}"
    },
    {
     "expr": "avg(rate(cilium_forward_count_total{k8s_app=\"cilium\", direction=\"INGRESS\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Forwarded"
    }
   ]
  },
  {
   "title": "Cilium L3 Ingress Packet Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"INGRESS\", k8s_app=\"cilium\", pod=~\"$pod\"}[$__rate_interval])) by (reason)",
     "legendFormat": "Reason: {{reason}}"
    },
    {
     "expr": "sum(rate(cilium_forward_count_total{direction=\"INGRESS\", k8s_app=\"cilium\", pod=~\"$pod\"}[$__rate_interval])) by (reason)",
     "legendFormat": "Forwarded"
    }
   ]
  },
  {
   "title": "Total Forwarded Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_bytes_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by ( direction)",
     "legendFormat": "{{pod}} {{direction}}"
    },
    {
     "expr": "sum(rate(cilium_forward_bytes_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Dropped Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_drop_bytes_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (reason, direction))",
     "legendFormat": "{{direction}} {{reason}}"
    }
   ]
  },
  {
   "title": "L7 forwarded request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_denied_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) ",
     "legendFormat": "denied"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_forwarded_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "forwarded"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_received_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Dropped Ingress Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"INGRESS\", k8s_app=\"cilium\", pod=~\"$pod\"}[$__rate_interval])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}