{
 "title": "Cilium / Overview",
 "description": "Dashboard for Cilium v1.12 (https://cilium.io/) Agent metrics",
 "tags": [
  "cilium-overview",
  "portefaix",
  "cilium",
  "cilium-mixin",
  "cni",
  "ebpf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cilium_version, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "label": "top k", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Top Cilium Agent Error Rates",
   "type": "stat",
   "description": "Tracks number of errors emitted during Cilium Agent runtime. Increased error rates could indicate issues with cilium.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, avg(rate(cilium_errors_warnings_total{k8s_app=\"cilium\", level=\"error\", pod=~\"$pod\"}[$__rate_interval])) by (pod, subsystem)) > 0",
     "legendFormat": "{{ pod }} {{subsystem}}"
    }
   ]
  },
  {
   "title": "Agent API Call Latency (95th Percentile)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Total Forwarded Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cilium_forward_bytes_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__range])) by (direction)",
     "legendFormat": "{{pod}} {{direction}}"
    }
   ]
  },
  {
   "title": "Packet Drop Reasons",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{}[$__rate_interval])) by (reason) / scalar(sum(rate(cilium_drop_count_total{}[$__rate_interval])) + 0.1) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BPF Map Operation Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Errors/Minute" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\", outcome=\"fail\",pod=~\"$pod\"}[$__rate_interval])) * 60",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "P95 Agent Controller Run Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, rate(cilium_controllers_runs_duration_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(cilium_controllers_runs_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Agent Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_errors_warnings_total{k8s_app=\"cilium\", level=\"error\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Top Agent Warnings Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "topk($k,  sum(rate(cilium_errors_warnings_total{k8s_app=\"cilium\", level=\"warning\", pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Allocated Identities",
   "type": "stat",
   "description": "Number identities allocated by type.\n\nLimits for identity allocations are:\n\nMax(cluster_local)=65280\nMax(node_local)=65535.\n\nRunning out of identities is a potentially critical issue.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Identities" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cilium_identity{pod=~\"$pod\"}) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(cilium_identity{pod=~\"$pod\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Top Drop Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, avg(rate(cilium_drop_count_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, direction))",
     "legendFormat": "{{pod}}:{{direction}}"
    }
   ]
  },
  {
   "title": "Top Pod Ingress Packet Forward",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_forward_count_total{k8s_app=\"cilium\", direction=\"INGRESS\", pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L7 Requests Forwarded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_denied_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) ",
     "legendFormat": "denied"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_forwarded_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "Forwarded Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_bytes_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by ( direction)",
     "legendFormat": "{{pod}} {{direction}}"
    },
    {
     "expr": "sum(rate(cilium_forward_bytes_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Agent Controller Runs",
   "type": "timeseries",
   "description": "This tracks internal controller runs within Cilium. Controllers are asynchronous controllers that attempt to reconcile Cilium state. Failing runs could indicate a problem with the agent.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Kubernetes Events Received/Consumed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (scope, action))",
     "legendFormat": "{{scope}} {{action}}"
    }
   ]
  },
  {
   "title": "BPF Map Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (outcome)",
     "legendFormat": "{{map_name}} {{outcome}}"
    }
   ]
  }
 ]
}