{
 "title": "Cilium / Components / FQDN Proxy",
 "description": "Dashboard for Cilium v1.12 (https://cilium.io/) Agent metrics",
 "tags": [
  "cilium-agent",
  "portefaix",
  "cilium",
  "cilium-mixin",
  "cni",
  "ebpf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cilium_version, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "label": "top k", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "P95 FQDN Proxy Upstream Reply Latency",
   "type": "timeseries",
   "description": "This is the P95 latency for FQDN upstream DNS request times. Increases here could indicate issues with upstream cluster DNS. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, rate(cilium_proxy_upstream_reply_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(cilium_proxy_upstream_reply_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "P95 FQDN Proxy Upstream Reply Latency",
   "type": "timeseries",
   "description": "This is the P95 latency for FQDN upstream DNS request times. Increases here could indicate issues with upstream cluster DNS. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, rate(cilium_proxy_upstream_reply_seconds_sum[$__rate_interval]) / rate(cilium_proxy_upstream_reply_seconds_count[$__rate_interval])) by (scope)",
     "legendFormat": "{{pod}}: {{scope}}"
    }
   ]
  },
  {
   "title": "P95  FQDN Proxy Upstream Reply Latency",
   "type": "timeseries",
   "description": "This is the P95 latency for FQDN upstream DNS request times. Increases here could indicate issues with upstream cluster DNS. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, rate(cilium_proxy_upstream_reply_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(cilium_proxy_upstream_reply_seconds_count{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}: {{scope}}"
    }
   ]
  },
  {
   "title": "Median  FQDN Proxy Upstream Reply Latency",
   "type": "timeseries",
   "description": "This is the P95 latency for FQDN upstream DNS request times. Increases here could indicate issues with upstream cluster DNS. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, rate(cilium_proxy_upstream_reply_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(cilium_proxy_upstream_reply_seconds_count{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}: {{scope}}"
    }
   ]
  }
 ]
}