{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    {{- include "kcc.annotations" . | indent 4 }}
  labels:
    {{- include "kcc.labels" . | indent 4 }}
  name: {{ .Values.alias }}-deletiondefender-cnrm-system-role
  namespace: {{ template "kcc.namespace" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    {{- include "kcc.annotations" . | indent 4 }}
  labels:
    {{- include "kcc.labels" . | indent 4 }}
  name: {{ .Values.alias }}-webhook-cnrm-system-role
  namespace: {{ template "kcc.namespace" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
  - delete
{{- end -}}
