---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "kcc.annotations" . | indent 4 }}
  labels:
    {{- include "kcc.labels" . | indent 4 }}
  name: {{ .Values.alias }}-deletiondefender
  namespace: {{ template "kcc.namespace" . }}
spec:
  ports:
  - name: deletiondefender
    port: 443
  selector:
    cnrm.cloud.google.com/component: cnrm-deletiondefender
    {{- include "kcc.selectorLabels" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "kcc.annotations" . | indent 4 }}
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
  labels:
    {{- include "kcc.labels" . | indent 4 }}
    cnrm.cloud.google.com/monitored: "true"
  name: {{ .Values.alias }}-manager
  namespace: {{ template "kcc.namespace" . }}
spec:
  ports:
  - name: controller-manager
    port: 443
  - name: metrics
    port: 8888
  selector:
    cnrm.cloud.google.com/component: cnrm-controller-manager
    {{- include "kcc.selectorLabels" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "kcc.annotations" . | indent 4 }}
    prometheus.io/port: "48797"
    prometheus.io/scrape: "true"
  labels:
    {{- include "kcc.labels" . | indent 4 }}
    cnrm.cloud.google.com/monitored: "true"
  name: {{ .Values.alias }}-resource-stats-recorder-service
  namespace: {{ template "kcc.namespace" . }}
spec:
  ports:
  - name: metrics
    port: 8888
    targetPort: 48797
  selector:
    cnrm.cloud.google.com/component: cnrm-resource-stats-recorder
    {{- include "kcc.selectorLabels" . | indent 4 }}