{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "kcc.annotations" . | indent 4 }}
  labels:
    {{- include "kcc.labels" . | indent 4 }}
  name: {{ .Values.alias }}-controller-manager
  namespace: {{ template "kcc.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "kcc.annotations" . | indent 4 }}
  labels:
    {{- include "kcc.labels" . | indent 4 }}
  name: {{ .Values.alias }}-deletiondefender
  namespace: {{ template "kcc.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "kcc.annotations" . | indent 4 }}
  labels:
    {{- include "kcc.labels" . | indent 4 }}
  name: {{ .Values.alias }}-resource-stats-recorder
  namespace: {{ template "kcc.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "kcc.annotations" . | indent 4 }}
  labels:
    {{- include "kcc.labels" . | indent 4 }}
  name: {{ .Values.alias }}-webhook-manager
  namespace: {{ template "kcc.namespace" . }}
{{- end -}}
