---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ko-1
spec:
  containers:
  - name: mycontainer
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      allowPrivilegeEscalation: true
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ko-2
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "echo ok"]
    securityContext:
      allowPrivilegeEscalation: true
  containers:
  - name: mycontainer
    image: gcr.io/google-samples/node-hello:1.0
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ok-1
spec:
  containers:
  - name: mycontainer
    image: gcr.io/google-samples/node-hello:1.0
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ok-2
spec:
  containers:
  - name: mycontainer
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      allowPrivilegeEscalation: false
