---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "fluvio.labels" . | nindent 4 }}
    {{- include "fluvio.sc.labels" . | nindent 4 }}
  name: fluvio
  namespace: {{ .Release.Namespace }}
data:
  fluvioClientConfig: |
    version = "2.0"
    current_profile = "k8s"

    [profile.k8-config-map-deployment]
    cluster = "k8s"

    [cluster.k8-config-map-deployment]
    endpoint = "fluvio-sc:{{ .Values.service.port }}"
    use_spu_local_address = true

    {{ if .Values.tls }}

    [cluster.k8s.tls]
    tls_policy = "verified"
    tls_source = "files"

    [cluster.k8s.tls.certs]
    domain = "{{ .Values.cert.domain }}"
    key = "/var/certs/client-tls/tls.key"
    cert = "/var/certs/client-tls/tls.crt"
    ca_cert = "/var/certs/ca/ca.crt"

    {{else}}

    [cluster.k8s.tls]
    tls_policy = "disabled"

    {{end}}
