---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "fluvio.labels" . | nindent 4 }}
    {{- include "fluvio.sc.labels" . | nindent 4 }}
  name: {{ template "fluvio.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "fluvio.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "fluvio.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
