# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v2
name: kubernetes-config-connector
description: A Helm chart for Google Kubernetes Config Connector (kcc)
home: https://charts.portefaix.xyz
# icon:
sources:
  - https://cloud.google.com/config-connector/docs/overview
type: application
keywords:
  - kubernetes-config-connector
  - kcc
  - krm
  - portefaix
version: 0.1.0
appVersion: 1.101.0
maintainers:
  - name: nlamirault
    email: nicolas.lamirault@gmail.com

# https://artifacthub.io/docs/topics/repositories/
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: kubernetes-config-connector
      image: gcr.io/cnrm-eap/recorder
    - name: kubernetes-config-connector
      image: gcr.io/cnrm-eap/webhook
    - name: kubernetes-config-connector
      image: gcr.io/cnrm-eap/controller
    - name: kubernetes-config-connector
      image: gcr.io/cnrm-eap/deletiondefender
  artifacthub.io/links: |
    - name: kubernetes-config-connector
      url: https://cloud.google.com/config-connector/docs/overview
    - name: Portefaix
      url: https://portefaix.xyz
  artifacthub.io/maintainers: |
    - name: nlamirault
      email: nicolas.lamirault@gmail.com
  artifacthub.io/signKey: |
    fingerprint: C39918B3EBDE35C23B8D0B8E5F99269A6FCA437C
    url: https://keybase.io/nlamirault/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: added
      description: Initialize chart
