# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "ack-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
  name: {{ include "ack-factory.name" . }}-eks-cluster
  namespace: {{ template "ack-factory.namespace" . }}
spec:
  name: {{ include "ack-factory.name" . }}-eks-cluster
  description: Portefaix EKS cluster
  maxSessionDuration: 3600
  policies:
  - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  assumeRolePolicyDocument: >
    {
      "Version":"2012-10-17",
      "Statement": [{
        "Effect":"Allow",
        "Principal": {
          "Service": [
            "ec2.amazonaws.com",
            "eks.amazonaws.com",
            "eks-fargate-pods.amazonaws.com",
            "lambda.amazonaws.com"
          ]
        },
        "Action": ["sts:AssumeRole"]
      }]
    }
  tags:
  {{- toYaml .Values.ack.tags | nindent 4 }}
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "ack-factory.labels" . | nindent 4 }}
  name: {{ include "ack-factory.name" . }}-eks-node
  namespace: {{ template "ack-factory.namespace" . }}
spec:
  name: {{ include "ack-factory.name" . }}-eks-node
  description: Portefaix EKS node
  maxSessionDuration: 3600
  policies:
  - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  assumeRolePolicyDocument: >
    {
      "Version":"2012-10-17",
      "Statement": [{
        "Effect":"Allow",
        "Principal": {
          "Service": [
            "ec2.amazonaws.com",
            "eks.amazonaws.com",
            "eks-fargate-pods.amazonaws.com",
            "lambda.amazonaws.com"
          ]
        },
        "Action": ["sts:AssumeRole"]
      }]
    }
  tags:
  {{- toYaml .Values.ack.tags | nindent 4 }}
