---
apiVersion: v2
name: quickwit
description: Sub-second search & analytics engine on cloud storage.
type: application
version: 0.1.1
appVersion: "v0.8.1"
keywords:
  - quickwit
  - search
  - analytics
  - tracing
  - logs
  - portefaix
home: https://quickwit.io/
sources:
  - https://github.com/nlamirault/portefaix-hub/tree/master/charts/quickwit
icon: https://avatars.githubusercontent.com/u/98504233?s=200&v=4
maintainers:
  - name: nlamirault
    email: nicolas.lamirault@gmail.com

# https://artifacthub.io/docs/topics/annotations/helm/
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: quickwit
      url: https://quickwit.io/
    - name: Portefaix
      url: https://portefaix.xyz
  artifacthub.io/maintainers: |
    - name: nlamirault
      email: nicolas.lamirault@gmail.com
  artifacthub.io/signKey: |
    fingerprint: C39918B3EBDE35C23B8D0B8E5F99269A6FCA437C
    url: https://keybase.io/nlamirault/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: fixed
      description: Additional labels for all resources
