{
 "title": "Loki / Bloom Build",
 "tags": [
  "loki-mixin",
  "monitoring-mixins-v1.12.0",
  "portefaix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster=~\"$cluster\"}, namespace)"
   },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "label_values(loki_bloomplanner_tenant_tasks_planned{cluster=\"$cluster\", namespace=\"$namespace\"}, tenant)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall progress",
   "type": "timeseries",
   "description": "Cell-wide compaction progress. Should increase till completion throughout each compaction period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(loki_bloomplanner_tenant_tasks_completed{cluster=~\"$cluster\", job=~\"$namespace/bloom-planner\"})\n/\nsum(loki_bloomplanner_tenant_tasks_planned{cluster=~\"$cluster\", job=~\"$namespace/bloom-planner\"})",
     "legendFormat": "Progress"
    }
   ]
  },
  {
   "title": "Progress by tenant",
   "type": "timeseries",
   "description": "Cell-wide compaction progress. Should increase till completion throughout each compaction period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (tenant) (loki_bloomplanner_tenant_tasks_completed{cluster=~\"$cluster\", job=~\"$namespace/bloom-planner\"})\n/\nsum by (tenant) (loki_bloomplanner_tenant_tasks_planned{cluster=~\"$cluster\", job=~\"$namespace/bloom-planner\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Errors Planner",
   "type": "logs",
   "description": "Blooms size vs uncompressed chunk size.",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} |= \"level=error\" |= \"component=bloom-planner\""
    }
   ]
  },
  {
   "title": "Errors Rate Planner",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} |= \"level=error\" |= \"component=bloom-planner\" [$__auto]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Errors Builder",
   "type": "logs",
   "description": "Blooms size vs uncompressed chunk size.",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} |= \"level=error\" |= \"component=bloom-builder\""
    }
   ]
  },
  {
   "title": "Errors Rate Builder",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} |= \"level=error\" |= \"component=bloom-builder\" [$__auto]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_bloomplanner_tenant_tasks_planned{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"}) > 0",
       "legendFormat": "Planned"
      },
      {
       "expr": "sum by (status) (loki_bloomplanner_tenant_tasks_completed{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"}) > 0",
       "legendFormat": "Completed - {{status}}"
      },
      {
       "expr": "loki_bloomplanner_inflight_tasks{cluster=\"$cluster\", job=\"$namespace/bloom-planner\", quantile=\"0.95\"}",
       "legendFormat": "inflight p95"
      },
      {
       "expr": "sum(loki_bloomplanner_queue_length{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"}) > 0",
       "legendFormat": "Queued"
      }
     ]
    },
    {
     "title": "Tasks per builder",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_bloomplanner_connected_builders{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"})",
       "legendFormat": "Connected builders"
      },
      {
       "expr": "count(loki_bloombuilder_processing_task{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} > 0)",
       "legendFormat": "Builders processing task"
      },
      {
       "expr": "count(loki_bloombuilder_processing_task{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} == 0)",
       "legendFormat": "IDLE Builders"
      }
     ]
    },
    {
     "title": "Series per task (includes series copied from other blocks)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.99, \n    sum by (le) (\n        rate(loki_bloombuilder_series_per_task_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.9, \n    sum by (le) (\n        rate(loki_bloombuilder_series_per_task_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.75, \n    sum by (le) (\n        rate(loki_bloombuilder_series_per_task_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p75"
      },
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.5, \n    sum by (le) (\n        rate(loki_bloombuilder_series_per_task_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Number of bytes from chunks added to blocks during each compaction.",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.99, \n    sum by (le) (\n        rate(loki_bloombuilder_bytes_per_task_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.9, \n    sum by (le) (\n        rate(loki_bloombuilder_bytes_per_task_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.5, \n    sum by (le) (\n        rate(loki_bloombuilder_bytes_per_task_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Tip",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 79 },
     "options": {
      "content": "Identify the tenant using the **_Progress by tenant_** panel from the overview and set tenant variable"
     }
    },
    {
     "title": "Tasks per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_bloomplanner_tenant_tasks_planned{cluster=\"$cluster\", job=\"$namespace/bloom-planner\", tenant=\"$tenant\"}) > 0",
       "legendFormat": "Planned"
      },
      {
       "expr": "sum by (status) (loki_bloomplanner_tenant_tasks_completed{cluster=\"$cluster\", job=\"$namespace/bloom-planner\", tenant=\"$tenant\"}) > 0",
       "legendFormat": "Completed - {{status}}"
      },
      {
       "expr": "sum(loki_bloomplanner_queue_length{cluster=\"$cluster\", job=\"$namespace/bloom-planner\", user=\"$tenant\"}) > 0",
       "legendFormat": "Queued"
      }
     ]
    },
    {
     "title": "Tenant errors",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "{cluster=~\"$cluster\", job=~\"$namespace/bloom-planner\"}\n|= \"level=error\"\n|= \"tenant=$tenant\""
      }
     ]
    }
   ]
  },
  {
   "title": "Bloom building",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tokens rate",
     "type": "timeseries",
     "description": "How many tokens each builder is appending to blooms. Accounts for tokens that are not actually added to the blooms since they are already there. See the panel on the right for a drill down on the collision.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(loki_bloom_tokens_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval]))\n/\nsum(count(loki_bloom_tokens_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}))",
       "legendFormat": "Per core"
      },
      {
       "expr": "sum(rate(loki_bloom_inserts_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "tokens/s by collision type",
     "type": "timeseries",
     "description": "Collision type may be `false` (no collision), `cache` (found in token cache) or true (found in bloom filter).\n\nType may be either `raw` (the original ngram) or `chunk_prefixed` (the ngram with the chunk prefix)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "# tokens/s by type+collision\nsum by (collision) (\n    rate(loki_bloom_inserts_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n) \n/ on () group_left\nsum (\n    rate(loki_bloom_inserts_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bloom size",
     "type": "timeseries",
     "description": "The sizes of the blooms created by the compactor. We build one bloom per series. The more unique ngrams and chunks the series has, the bigger their blooms will be.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n    1.0,\n    sum by (le) (\n        rate(loki_bloom_size_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_quantile(\n    0.99, \n    sum by (le) (\n        rate(loki_bloom_size_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.50, \n    sum by (le) (\n        rate(loki_bloom_size_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Chunks indexed",
     "type": "timeseries",
     "description": "How many chunks are we indexing in the blooms. Either:\n- `copied` from a pre-existing bloom block, or \n- `iterated` through all its entries if processed for the first time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "# chunks indexed, by iteration or copied from a pre-existing bloom\nsum(rate(loki_bloom_chunks_indexed_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval])) by (type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Builder Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Required CPUs to not lag behind",
     "type": "timeseries",
     "description": "Shows the expected number of cpu cores we need to provision to build blooms as fast as we ingest data so a build iteration doesn't take longer than the build interval.\n\nWe may decide to have more to speed up building blooms.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2030 },
     "targets": [
      {
       "expr": "# This query shows the expected number of cpu cores we need to not fall behind\n# building blooms for data we're ingesting.\n# conceptually, the formula is:\n# (cell_bytes * space_amplification / bloom_bytes_processed_per_core)\n\n# number of replicas needed\nsum(avg_over_time(loki_cell:bytes:rate1m{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))\n*\n## Space amplification (how much data do we write compared to what we ingest?)\n(\n  # rep factor\n  3 *\n  sum(\n    # 1 - dedupe_ratio\n    1 - \n    sum(rate(loki_chunk_store_deduped_chunks_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (cluster, namespace)\n    /\n    sum(rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (cluster, namespace)\n  )\n)\n/\n(\nsum(rate(loki_bloombuilder_chunk_series_size_sum{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-builder\"}[$__rate_interval]))\n/\nsum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-builder\"}[$__rate_interval]))\n)",
       "legendFormat": "Needed"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-builder\"}[$__rate_interval]))",
       "legendFormat": "Available"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\", resource=\"cpu\"} > 0)\n*\ncount(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\", resource=\"cpu\"} > 0)",
       "legendFormat": "Provisioned"
      }
     ]
    },
    {
     "title": "MB/s per core",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2030 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "# MB/s/core chunk data processed\nsum(rate(loki_bloombuilder_chunk_series_size_sum{cluster=~\"$cluster\", job=~\"$namespace/bloom-builder\"}[$__rate_interval]))\n/\nsum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-builder\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2037 },
     "targets": [
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\", resource=\"cpu\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\", resource=\"cpu\"} > 0)",
       "legendFormat": "Limit"
      },
      {
       "expr": "quantile(\n    0.99,\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}[$__rate_interval])\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile(\n    0.50,\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}[$__rate_interval])\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "avg(\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}[$__rate_interval])\n)",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}[$__rate_interval])\n)",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "CPU per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2037 },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\", resource=\"cpu\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\", resource=\"cpu\"} > 0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory (workingset)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2044 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\", resource=\"memory\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"} > 0)",
       "legendFormat": "Limit"
      },
      {
       "expr": "quantile (\n  0.99,\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile (\n  0.50,\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "avg (\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}\n)",
       "legendFormat": "Avg"
      },
      {
       "expr": "max (\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}\n)",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory per pod (workingset)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2044 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\", resource=\"memory\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"} > 0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2051 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (\n    increase(\n        kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-builder\"}[10m]\n    )\n) > 0",
       "legendFormat": "Restarts"
      }
     ]
    },
    {
     "title": "Container restarts reason per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2051 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(\n    sum by (pod) (\n        increase(\n            kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-builder\"}[10m]\n        )\n    )\n    * on (pod) group_right\n    max by (pod, reason) (\n        kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-builder\"}\n    )\n) > 0",
       "legendFormat": "{{reason}} / {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Planner Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2302 },
     "targets": [
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\", resource=\"cpu\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\", resource=\"cpu\"} > 0)",
       "legendFormat": "Limit"
      },
      {
       "expr": "quantile(\n    0.99,\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\"}[$__rate_interval])\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile(\n    0.50,\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\"}[$__rate_interval])\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "avg(\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\"}[$__rate_interval])\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "CPU per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2302 },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\", resource=\"cpu\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\", resource=\"cpu\"} > 0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory (workingset)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2309 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\", resource=\"memory\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\"} > 0)",
       "legendFormat": "Limit"
      },
      {
       "expr": "quantile (\n  0.99,\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\"}\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile (\n  0.50,\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "avg (\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-builder\"}\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Memory per pod (workingset)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2309 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\", resource=\"memory\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-planner\"} > 0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2316 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (\n    increase(\n        kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-planner\"}[10m]\n    )\n) > 0",
       "legendFormat": "Restarts"
      }
     ]
    },
    {
     "title": "Container restarts reason per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2316 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(\n    sum by (pod) (\n        increase(\n            kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-planner\"}[10m]\n        )\n    )\n    * on (pod) group_right\n    max by (pod, reason) (\n        kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-planner\"}\n    )\n) > 0",
       "legendFormat": "{{reason}} / {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metas building",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Created Metas",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 2497 },
     "targets": [
      {
       "expr": "sum(increase(loki_bloombuilder_metas_created_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval]))",
       "legendFormat": "Metas"
      }
     ]
    },
    {
     "title": "Created Metas",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 2497 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(loki_bloombuilder_metas_created_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__range]))",
       "legendFormat": "Metas"
      }
     ]
    },
    {
     "title": "Deleted Metas",
     "type": "timeseries",
     "description": "Compactors delete metas and blocks marked for deletion in the metas tombstones.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2497 },
     "targets": [
      {
       "expr": "sum by (phase) (increase(loki_bloomplanner_metas_deleted_total{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"}[$__rate_interval]))",
       "legendFormat": "Deleted during {{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks building",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Created Blocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 2505 },
     "targets": [
      {
       "expr": "sum(increase(loki_bloombuilder_blocks_created_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval]))",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Created Blocks",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 2505 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(loki_bloombuilder_blocks_created_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__range]))",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Deleted Blocks",
     "type": "timeseries",
     "description": "Compactors delete metas and blocks marked for deletion in the metas tombstones.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2505 },
     "targets": [
      {
       "expr": "sum by (phase) (increase(loki_bloomplanner_blocks_deleted_total{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"}[$__rate_interval]))",
       "legendFormat": "Deleted during {{phase}}"
      }
     ]
    },
    {
     "title": "Blocks reused",
     "type": "timeseries",
     "description": "Number of overlapping bloom blocks reused when creating new blocks\n",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2512 },
     "targets": [
      {
       "expr": "sum(increase(loki_bloombuilder_blocks_reused_total{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"}[$__rate_interval]))",
       "legendFormat": "Blocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Retention",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running now?",
     "type": "stat",
     "description": "Is the retention currently running?",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2573 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (cluster, namespace) (loki_bloomplanner_retention_running{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Retention running",
     "type": "timeseries",
     "description": "Is the retention currently running?",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 2573 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "sum by (cluster, namespace) (loki_bloomplanner_retention_running{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Retention time",
     "type": "timeseries",
     "description": "How much time applying retention took",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2573 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, \n  sum by (status, le) (\n    rate(loki_bloomplanner_retention_time_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2581 },
     "options": {
      "content": "During the planning phase, the planner downloads the metas and TSDBs to build the plan.\n\nOnce all blocks and metas are built, the builder flushes them to the object store.\n\nAfter each iteration, the planner deletes the metas and blocks marked for deletion in the tombstones."
     }
    },
    { "type": "text", "gridPos": { "h": 13, "w": 2, "x": 0, "y": 2585 }, "options": { "content": "---\n#### GCS\n" } },
    {
     "title": "QPS Planner",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 2585 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (container, status_code, operation) (rate(loki_gcs_request_duration_seconds_count{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency Planner",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2585 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    },
    {
     "title": "QPS Builder",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 2592 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (container, status_code, operation) (rate(loki_gcs_request_duration_seconds_count{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency Planner",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2592 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 14, "w": 2, "x": 0, "y": 2598 }, "options": { "content": "---\n#### S3\n" } },
    {
     "title": "QPS Planner",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 2599 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(loki_s3_request_duration_seconds_count{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency Planner",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2599 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\", job=\"\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    },
    {
     "title": "QPS Builder",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 2606 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(loki_s3_request_duration_seconds_count{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency Builder",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2606 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 2612 }, "options": { "content": "---\n#### Azure\nBlob Storage" } },
    {
     "title": "QPS Planner",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 2613 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(loki_azure_blob_request_duration_seconds_count{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency Planner",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2613 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-planner\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    },
    {
     "title": "QPS Builder",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 2620 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(loki_azure_blob_request_duration_seconds_count{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency Builder",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2620 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"$namespace/bloom-builder\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    }
   ]
  }
 ]
}