# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}-cluster
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  forProvider:
    description: "IAM ROLE EKS for {{ include "crossplane-aws-factory.fullname" . }} cluster"
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com",
                        "eks.amazonaws.com",
                        "eks-fargate-pods.amazonaws.com",
                        "lambda.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }
    tags:
      {{- include "crossplane-aws-factory.awsTags" . | nindent 6 }}
      - key: Name
        value: {{ include "crossplane-aws-factory.name" . }}-cluster
      - key: Service
        value: kubernetes
  deletionPolicy: Delete
  writeConnectionSecretToRef:
    name: {{ include "crossplane-aws-factory.name" . }}-iam-role-cluster
    namespace: {{ .Values.crossplane.namespace }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" . }}
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}-eks-node
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  forProvider:
    description: "IAM ROLE NodeGroup for {{ include "crossplane-aws-factory.fullname" . }} cluster"
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }
    tags:
      {{- include "crossplane-aws-factory.awsTags" . | nindent 6 }}
      - key: Name
        value: {{ include "crossplane-aws-factory.name" . }}-eks-node
      - key: Service
        value: kubernetes
  deletionPolicy: Delete
  writeConnectionSecretToRef:
    name: {{ include "crossplane-aws-factory.name" . }}-iam-role-eks-node
    namespace: {{ .Values.crossplane.namespace }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" . }}
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}-controlplane
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleNameRef:
      name: {{ include "crossplane-aws-factory.name" . }}-eks-cluster
  writeConnectionSecretToRef:
    name: {{ include "crossplane-aws-factory.name" . }}-iam-role-eks-cluster
    namespace: {{ .Values.crossplane.namespace }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" . }}
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}-service
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
    roleNameRef:
      name: {{ include "crossplane-aws-factory.name" . }}-eks-cluster
  writeConnectionSecretToRef:
    name: {{ include "crossplane-aws-factory.name" . }}-iam-role-service
    namespace: {{ .Values.crossplane.namespace }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" . }}
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}-worker
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    roleNameRef:
      name: {{ include "crossplane-aws-factory.name" . }}-node
  writeConnectionSecretToRef:
    name: {{ include "crossplane-aws-factory.name" . }}-iam-role-worker
    namespace: {{ .Values.crossplane.namespace }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" . }}
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}-cni
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    roleNameRef:
      name: {{ include "crossplane-aws-factory.name" . }}-node
  writeConnectionSecretToRef:
    name: {{ include "crossplane-aws-factory.name" . }}-iam-role-cni
    namespace: {{ .Values.crossplane.namespace }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" . }}
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: {{ include "crossplane-aws-factory.name" . }}-registry
  namespace: {{ template "crossplane-aws-factory.namespace" . }}
  labels:
    {{- include "crossplane-aws-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: iam
{{- with .Values.additionalAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    roleNameRef:
      name: {{ include "crossplane-aws-factory.name" . }}-node
  writeConnectionSecretToRef:
    name: {{ include "crossplane-aws-factory.name" . }}-iam-role-registry
    namespace: {{ .Values.crossplane.namespace }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" . }}