# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

{{- $baseName := include "crossplane-aws-factory.name" $ }}
{{- $region := .Values.aws.region }}
{{- $namespace := include "crossplane-aws-factory.namespace" . }}
{{ range .Values.aws.sns.topics }}
{{- $topicName := printf "%s-%s" $baseName .name -}}
---
apiVersion: sns.aws.crossplane.io/v1beta1
kind: Topic
metadata:
  name: {{ $topicName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "crossplane-aws-factory.labels" $ | nindent 4 }}
    app.kubernetes.io/component: sns
  {{- with $.Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  forProvider:
    region: {{ $region }}
    name: {{ $topicName }}
    tags:
      {{- include "crossplane-aws-factory.awsTags" $ | nindent 6 }}
      - key: Name
        value: {{ $topicName }}
    displayName: {{ $topicName }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" $ }}
{{ end }}
{{- $baseName := include "crossplane-aws-factory.name" $ }}
{{- $region := .Values.aws.region }}
{{- $namespace := include "crossplane-aws-factory.namespace" . }}
{{ range .Values.aws.sns.subscriptions }}
{{- $subscriptionName := printf "%s-%s" $baseName .name -}}
---
apiVersion: sns.aws.crossplane.io/v1beta1
kind: Subscription
metadata:
  name: {{ $subscriptionName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "crossplane-aws-factory.labels" $ | nindent 4 }}
    app.kubernetes.io/component: sns
  {{- with $.Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  forProvider:
    region: {{ $region }}
    protocol: {{ .protocol }}
    endpoint: {{ .endpoint }}
    topicArnRef:
      name: {{ printf "%s-%s" $baseName .topicName }}
  providerConfigRef:
    name: {{ include "crossplane-aws-factory.name" $ }}
{{ end }}