{{- if and .Values.api.enabled .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openmemory.fullname" . }}-api
  labels:
    {{- include "openmemory.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openmemory.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
