{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmemory.fullname" . }}-api
  labels:
    {{- include "openmemory.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "openmemory.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
