{
 "title": "OSM Workload to Workload Metrics",
 "description": "Compatible with OSM v1.0.0. This dashboard displays the latencies of requests in the mesh from workload to workload.",
 "tags": [
  "osm",
  "osm-mixin",
  "service-mesh",
  "portefaix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_namespace",
    "label": "Source Namespace",
    "query": "label_values(osm_request_duration_ms_sum{}, source_namespace)"
   },
   {
    "name": "source_workload_kind",
    "label": "Source Workload Kind",
    "query": "label_values(osm_request_duration_ms_sum{source_namespace=\"$source_namespace\"},source_kind)"
   },
   {
    "name": "source_workload_name",
    "label": "Source Workload Name",
    "query": "label_values(osm_request_duration_ms_sum{source_namespace=\"$source_namespace\", source_kind=\"$source_workload_kind\"}, source_name)"
   },
   {
    "name": "source_pod",
    "label": "Source Pod",
    "query": {
     "query": "label_values(osm_request_duration_ms_sum{source_namespace=\"$source_namespace\", source_kind=\"$source_workload_kind\",source_name=\"$source_workload_name\"}, source_pod) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Latency (P99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(irate(osm_request_duration_ms_bucket{source_namespace=\"$source_namespace\",source_kind=\"$source_workload_kind\",source_name=\"$source_workload_name\",source_pod=\"$source_pod\"}[1m])) by (le, destination_namespace, destination_name))",
     "legendFormat": "{{destination_namespace}}/{{destination_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (P90)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(irate(osm_request_duration_ms_bucket{source_namespace=\"$source_namespace\",source_kind=\"$source_workload_kind\",source_name=\"$source_workload_name\",source_pod=\"$source_pod\"}[1m])) by (le, destination_namespace, destination_name))",
     "legendFormat": "{{destination_namespace}}/{{destination_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (P50)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,sum(irate(osm_request_duration_ms_bucket{source_namespace=\"$source_namespace\",source_kind=\"$source_workload_kind\",source_name=\"$source_workload_name\",source_pod=\"$source_pod\"}[1m])) by (le, destination_namespace, destination_name))",
     "legendFormat": "{{destination_namespace}}/{{destination_name}}"
    }
   ]
  }
 ]
}