{{- if .Values.destination.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.destination.secret.name }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    {{- include "olake.cron.labels" . | nindent 4 }}
type: Opaque
stringData:
  destination.json: |
    {{ tpl (.Values.destination.config | toJson) . }}
{{- end }}
