{{- if .Values.destination.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.destination.secretName }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "olake.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: configuration
type: Opaque
stringData:
  destination.json: |
    {
      "type": "{{ .Values.destination.config.type }}",
      "writer": {
        "catalog_type": "{{ .Values.destination.config.writer.catalog_type }}",
        "normalization": {{ .Values.destination.config.writer.normalization }},
        "iceberg_s3_path": "{{ .Values.destination.secrets.iceberg_s3_path }}",
        "aws_region": "{{ .Values.destination.secrets.aws_region }}",
        "aws_access_key": "{{ .Values.destination.secrets.aws_access_key }}",
        "aws_secret_key": "{{ .Values.destination.secrets.aws_secret_key }}",
        "iceberg_db": "{{ .Values.destination.secrets.iceberg_db }}",
        "grpc_port": {{ .Values.destination.config.writer.grpc_port }},
        "server_host": "{{ .Values.destination.config.writer.server_host }}"
      }
    }
{{- end }}