---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ok-1
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ok-2
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      runAsNonRoot: true
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "echo ok"]
    securityContext:
      runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ko-1
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ko-2
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      runAsNonRoot: false
