---
# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Project / Projects Issues

on: # yamllint disable-line rule:truthy
  issues:
    types:
    - opened
    - labeled

jobs:
  issues:
    name: Add issue to Project
    runs-on: ubuntu-latest
    steps:
    - name: Monitor Actions
      uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}
    - uses: actions/add-to-project@v0.6.1
      with:
        project-url: https://github.com/orgs/portefaix/projects/6
        github-token: ${{ secrets.ACTIONS_PAT }}

  # cloud-aws:
  #   name: Add issue to Project AWS
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Monitor Actions
  #     uses: GitHubSecurityLab/actions-permissions/monitor@v1
  #     with:
  #       config: ${{ vars.PERMISSIONS_CONFIG }}
  #   - uses: actions/add-to-project@v0.6.0
  #     with:
  #       project-url: https://github.com/orgs/portefaix/projects/3
  #       github-token: ${{ secrets.ACTIONS_PAT }}
  #       labeled: cloud/aws
  #       label-operator: OR

  # cloud-azure:
  #   name: Add issue to Project Azure
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Monitor Actions
  #     uses: GitHubSecurityLab/actions-permissions/monitor@v1
  #     with:
  #       config: ${{ vars.PERMISSIONS_CONFIG }}
  #   - uses: actions/add-to-project@v0.6.0
  #     with:
  #       project-url: https://github.com/orgs/portefaix/projects/5
  #       github-token: ${{ secrets.ACTIONS_PAT }}
  #       labeled: cloud/azure
  #       label-operator: OR

  # cloud-gcp:
  #   name: Add issue to Project GCP
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Monitor Actions
  #     uses: GitHubSecurityLab/actions-permissions/monitor@v1
  #     with:
  #       config: ${{ vars.PERMISSIONS_CONFIG }}
  #   - uses: actions/add-to-project@v0.6.0
  #     with:
  #       project-url: https://github.com/orgs/portefaix/projects/4
  #       github-token: ${{ secrets.ACTIONS_PAT }}
  #       labeled: cloud/gcp
  #       label-operator: OR

  # cloud-homelab:
  #   name: Add issue to Project Homelab
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Monitor Actions
  #     uses: GitHubSecurityLab/actions-permissions/monitor@v1
  #     with:
  #       config: ${{ vars.PERMISSIONS_CONFIG }}
  #   - uses: actions/add-to-project@v0.6.0
  #     with:
  #       project-url: https://github.com/orgs/portefaix/projects/6
  #       github-token: ${{ secrets.ACTIONS_PAT }}
  #       labeled: cloud/homelab
  #       label-operator: OR

  # kubernetes:
  #   name: Add issue to Project Kubernetes
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Monitor Actions
  #     uses: GitHubSecurityLab/actions-permissions/monitor@v1
  #     with:
  #       config: ${{ vars.PERMISSIONS_CONFIG }}
  #   - uses: actions/add-to-project@v0.6.0
  #     with:
  #       project-url: https://github.com/orgs/portefaix/projects/14
  #       github-token: ${{ secrets.ACTIONS_PAT }}
  #       labeled: area/kubernetes
  #       label-operator: OR

  # terraform:
  #   name: Add issue to Project Terraform
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Monitor Actions
  #     uses: GitHubSecurityLab/actions-permissions/monitor@v1
  #     with:
  #       config: ${{ vars.PERMISSIONS_CONFIG }}
  #   - uses: actions/add-to-project@v0.6.0
  #     with:
  #       project-url: https://github.com/orgs/portefaix/projects/15
  #       github-token: ${{ secrets.ACTIONS_PAT }}
  #       labeled: area/terraform
  #       label-operator: OR
