---
name: Project / Renovate

on:
  schedule:
    - cron: '0 * * * 0'
  workflow_dispatch:

env:
  RENOVATE_CONFIG_FILE: .github/renovate.json5

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Renovate
        uses: renovatebot/github-action@eaf12548c13069dcc28bb75c4ee4610cdbe400c5 # v44.2.6
        env:
          RENOVATE_ALLOWED_COMMANDS: '["./hack/chart-version.sh"]'
