# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  {{- with $.Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "kcc-factory.labels" $ | nindent 4 }}
  name: {{ include "kcc-factory.name" . }}-allow-tcp-ssh-icmp
  namespace: {{ template "kcc-factory.namespace" . }}
spec:
  allow:
    - protocol: tcp
      ports:
       - "22"
       - "3389"
    - protocol: icmp
  networkRef:
    name: {{ include "kcc-factory.name" . }}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  {{- with $.Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "kcc-factory.labels" $ | nindent 4 }}
  name: {{ include "kcc-factory.name" . }}-internal
  namespace: {{ template "kcc-factory.namespace" . }}
spec:
  allow:
    - protocol: tcp
    - protocol: icmp
    - protocol: udp
  networkRef:
    name: {{ include "kcc-factory.name" . }}
  sourceRanges:
    - {{ .Values.kcc.network.ipCidrRange }}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  {{- with $.Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "kcc-factory.labels" $ | nindent 4 }}
  name: {{ include "kcc-factory.name" . }}-allow-iap-ssh
  namespace: {{ template "kcc-factory.namespace" . }}
spec:
  priority: 10000
  allow:
    - ports:
        - "22"
      protocol: tcp
  direction: INGRESS
  disabled: false
  enableLogging: false
  networkRef:
    name: {{ include "kcc-factory.name" . }}
  sourceRanges:
    - "35.235.240.0/20"
  targetTags:
    - allow-iap-ssh
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  {{- with $.Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "kcc-factory.labels" $ | nindent 4 }}
  name: {{ include "kcc-factory.name" . }}-allow-gcp-lb
  namespace: {{ template "kcc-factory.namespace" . }}
spec:
  priority: 10000
  allow:
    - ports:
        - "80"
        - "443"
        - "8080"
      protocol: tcp
  direction: INGRESS
  disabled: false
  enableLogging: false
  networkRef:
    name: {{ include "kcc-factory.name" . }}
  sourceRanges:
    - "35.191.0.0/16"
    - "130.211.0.0/22"
    - "209.85.152.0/22"
    - "209.85.204.0/22"
  targetTags:
    - allow-gcp-lb
