# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  {{- with $.Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "kcc-factory.labels" $ | nindent 4 }}
  name: {{ include "kcc-factory.name" . }}
  namespace: {{ template "kcc-factory.namespace" . }}
spec:
  description: {{ include "kcc-factory.name" . }}
  location: {{ .Values.kcc.gke.location }}
  releaseChannel:
    channel: {{ .Values.kcc.gke.releaseChannel }}
  networkRef:
    name: {{ include "kcc-factory.name" . }}
  subnetworkRef:
    name: {{ include "kcc-factory.name" . }}

  workloadIdentityConfig:
    workloadPool: {{ include "kcc-factory.name" . }}.svc.id.goog

  # Automation

  {{- with .Values.kcc.gke.clusterAutoscaling }}
  clusterAutoscaling:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  verticalPodAutoscaling:
    enabled: {{ .Values.kcc.gke.verticalPodAutoscaling.enabled }}
  {{- with .Values.kcc.gke.maintenancePolicy }}
  maintenancePolicy:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kcc.gke.notificationConfig }}
  notificationConfig:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  

  # Default Node Pool

  initialNodeCount: {{ .Values.kcc.gke.defaultNodepools.initialNodeCount }}
  defaultMaxPodsPerNode: {{ .Values.kcc.gke.defaultNodepools.defaultMaxPodsPerNode }}
  {{- with .Values.kcc.gke.defaultNodepools.nodeLocations }}
  nodeLocations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Networking

  networkingMode: {{ .Values.kcc.gke.networkingMode }}
  # Enable dataplane V2
  # https://cloud.google.com/kubernetes-engine/docs/concepts/dataplane-v2
  datapathProvider: {{ .Values.kcc.gke.datapathProvider }}
  {{- with .Values.kcc.gke.masterAuthorizedNetworksConfig }}
  masterAuthorizedNetworksConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kcc.gke.ipAllocationPolicy }}
  ipAllocationPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  enableIntranodeVisibility: true
  {{- with .Values.kcc.gke.ipAllocationPolicy }}
  ipAllocationPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  networkPolicy:
    enabled: {{ .Values.kcc.gke.networkPolicy.enabled }}
  dnsConfig:
    clusterDns: CLOUD_DNS
    clusterDnsScope: CLUSTER_SCOPE

  # Security

  enableBinaryAuthorization: true
  enableShieldedNodes: true
  confidentialNodes:
    enabled: true
  privateClusterConfig:
    # Allow public access to the GKE control plane by default.
    # This default is a deliberate compromise for ease of use over security.
    # For increased security, set to true to disable public IP access.
    enablePrivateEndpoint: false
    enablePrivateNodes: true
    # Enable global access to the GKE control plane's internal loab balancer.
    # https://cloud.google.com/load-balancing/docs/internal/setting-up-internal#ilb-global-access
    masterGlobalAccessConfig:
      enabled: true
    masterIpv4CidrBlock: 172.16.0.0/28
  podSecurityPolicyConfig:
    enabled: false

  # Features

  loggingConfig:
    enableComponents:
      - "SYSTEM_COMPONENTS"
      - "WORKLOADS"
  monitoringConfig:
    enableComponents:
      - "SYSTEM_COMPONENTS"
  enableAutopilot: false
  costManagementConfig:
    enabled: true
  addonsConfig:
    cloudrunConfig:
      disabled: true
    configConnectorConfig:
      enabled: false
    dnsCacheConfig:
      enabled: true
    gcePersistentDiskCsiDriverConfig:
      enabled: true
    gcpFilestoreCsiDriverConfig:
      enabled: true
    gkeBackupAgentConfig:
      enabled: true
    horizontalPodAutoscaling:
      disabled: true
    httpLoadBalancing:
      disabled: true
    istioConfig:
      disabled: true
    kalmConfig:
      enabled: false
    networkPolicyConfig:
      disabled: false
{{- $baseName := include "kcc-factory.name" $ }}
{{- $namespace := include "kcc-factory.namespace" . }}
{{ range .Values.kcc.gke.nodepools }}
{{- $nodepoolName := printf "%s-%s" $baseName .name -}}
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  {{- with $.Values.additionalAnnotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "kcc-factory.labels" $ | nindent 4 }}
  name: {{ $nodepoolName }}
  namespace: {{ $namespace }}
spec:
  location: {{ $.Values.kcc.gke.location }}
  {{- with .autoscaling }}
  autoscaling:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  nodeConfig:
    imageType: COS_CONTAINERD
    machineType: {{ .machineType }}
    diskSizeGb: {{ .diskSizeGb }}
    diskType: {{ .diskType }}
    labels:
      gke.io/nodepool: {{ .name }}
    tags:
      - kubernetes
      - nodes
    preemptible: {{ .preemptible }}
    minCpuPlatform: "Intel Haswell"
    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
      # - https://www.googleapis.com/auth/logging.write
      # - https://www.googleapis.com/auth/monitoring
    metadata:
      disable-legacy-endpoints: "true"
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    serviceAccountRef:
      name: {{ include "kcc-factory.name" $ }}-gke
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: {{ include "kcc-factory.name" $ }}
{{ end }}
